PRAGMA foreign_keys = ON;

-- Unit Registry Seed Data (GENERATED -- do not edit by hand)
-- Regenerate with: python3 scripts/generate_unit_registry.py
-- Source of truth: SiennaSchemas Core/units.json + schema/column_conventions.json
-- Must run AFTER schema.sql and triggers.sql, BEFORE views.sql.

-- 1. Quantity types
INSERT INTO quantity_types (name, default_unit, dimension, description) VALUES
    ('ActivePower', 'MW', '{"L":2,"M":1,"T":-3}', 'Active (real) power'),
    ('ActivePowerChangeRate', 'MW/min', '{"L":2,"M":1,"T":-4}', 'Rate of change of active power (ramp)'),
    ('Angle', 'rad', '{}', 'Angle (allowed units rad and deg)'),
    ('ApparentPower', 'MVA', '{"L":2,"M":1,"T":-3}', 'Apparent power'),
    ('CO2Emissions', 't/MMBtu', '{"Btu":-1,"M":1}', 'CO2 emission rate (mass per unit of fuel energy)'),
    ('Capacitance', 'F', '{"I":2,"L":-2,"M":-1,"T":4}', 'Capacitance'),
    ('Conductance', 'S', '{"I":2,"L":-2,"M":-1,"T":3}', 'Conductance'),
    ('CostPerCapacity', 'USD/MW', '{"L":-2,"M":-1,"T":3,"USD":1}', 'Cost per unit of capacity (capital cost)'),
    ('CostPerEnergy', 'USD/MWh', '{"L":-2,"M":-1,"T":2,"USD":1}', 'Cost per unit of energy (operation / energy capital cost)'),
    ('CostPerLevel', 'USD/m', '{"L":-1,"USD":1}', 'Cost per unit of hydraulic head (e.g. reservoir operation cost when level_data_type=HEAD)'),
    ('CostPerMass', 'USD/t', '{"M":-1,"USD":1}', 'Cost per unit of mass (e.g. carbon price or tax)'),
    ('CostPerTime', 'USD/h', '{"T":-1,"USD":1}', 'Cost per unit of time'),
    ('CostPerVolume', 'USD/m3', '{"L":-3,"USD":1}', 'Cost per unit of volume (e.g. reservoir operation cost)'),
    ('CurrentFlow', 'kA', '{"I":1}', 'Current flow'),
    ('Dimensionless', '1', '{}', 'Dimensionless quantity'),
    ('Duration', 'h', '{"T":1}', 'Duration (allowed units h, yr, min, s)'),
    ('ElectricalEnergy', 'MWh', '{"L":2,"M":1,"T":-2}', 'Real (electrical) energy'),
    ('Elevation', 'm', '{"L":1}', 'Elevation / hydraulic head'),
    ('EmissionRate', 't/MWh', '{"L":-2,"T":2}', 'Emission mass per unit of electrical energy'),
    ('Fraction', '1', '{}', 'Fractional quantity (efficiency, losses, cofire level, etc.)'),
    ('Frequency', 'Hz', '{"T":-1}', 'Frequency'),
    ('HeadRate', 'm/s', '{"L":1,"T":-1}', 'Rate of change of hydraulic head'),
    ('HeatRate', 'MMBtu/MWh', '{"Btu":1,"L":-2,"M":-1,"T":2}', 'Heat rate (fuel energy per unit of electrical energy)'),
    ('Impedance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Impedance'),
    ('Inductance', 'H', '{"I":-2,"L":2,"M":1,"T":-2}', 'Inductance'),
    ('Length', 'km', '{"L":1}', 'Length'),
    ('Mass', 't', '{"M":1}', 'Mass'),
    ('Money', 'USD', '{"USD":1}', 'Monetary value'),
    ('PowerFactor', '1', '{}', 'Power factor'),
    ('PowerPerFrequency', 'MW/Hz', '{"L":2,"M":1,"T":-2}', 'Active power response per unit of frequency deviation (regulation / droop participation)'),
    ('Reactance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Reactance'),
    ('ReactivePower', 'MVAr', '{"L":2,"M":1,"T":-3}', 'Reactive power'),
    ('Resistance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Resistance'),
    ('StartFuelPerCapacity', 'MMBtu/MW', '{"Btu":1,"L":-2,"M":-1,"T":3}', 'Start-up fuel per unit of capacity'),
    ('Susceptance', 'S', '{"I":2,"L":-2,"M":-1,"T":3}', 'Susceptance'),
    ('Voltage', 'kV', '{"I":-1,"L":2,"M":1,"T":-3}', 'Voltage'),
    ('Volume', 'm3', '{"L":3}', 'Volume'),
    ('VolumeFlowRate', 'm3/s', '{"L":3,"T":-1}', 'Volumetric flow rate');

-- 2. Allowed (quantity_type, unit) vocabulary
INSERT INTO allowed_units (quantity_type, unit) VALUES
    ('ActivePower', 'MW'),
    ('ActivePowerChangeRate', 'MW/min'),
    ('Angle', 'deg'),
    ('Angle', 'rad'),
    ('ApparentPower', 'MVA'),
    ('CO2Emissions', 't/MMBtu'),
    ('Capacitance', 'F'),
    ('Conductance', 'S'),
    ('Conductance', 'pu'),
    ('CostPerCapacity', 'USD/MW'),
    ('CostPerEnergy', 'USD/MWh'),
    ('CostPerLevel', 'USD/m'),
    ('CostPerMass', 'USD/t'),
    ('CostPerTime', 'USD/h'),
    ('CostPerVolume', 'USD/m3'),
    ('CurrentFlow', 'A'),
    ('CurrentFlow', 'kA'),
    ('Dimensionless', '1'),
    ('Duration', 'h'),
    ('Duration', 'min'),
    ('Duration', 's'),
    ('Duration', 'yr'),
    ('ElectricalEnergy', 'MJ'),
    ('ElectricalEnergy', 'MWh'),
    ('Elevation', 'm'),
    ('EmissionRate', 'Mt/MWh'),
    ('EmissionRate', 't/MWh'),
    ('Fraction', '1'),
    ('Frequency', 'Hz'),
    ('HeadRate', 'm/s'),
    ('HeatRate', 'MMBtu/MWh'),
    ('Impedance', 'ohm'),
    ('Inductance', 'H'),
    ('Length', 'km'),
    ('Length', 'm'),
    ('Mass', 'Mt'),
    ('Mass', 'kg'),
    ('Mass', 'lb'),
    ('Mass', 'ston'),
    ('Mass', 't'),
    ('Money', 'USD'),
    ('PowerFactor', '1'),
    ('PowerPerFrequency', 'MW/Hz'),
    ('Reactance', 'ohm'),
    ('Reactance', 'pu'),
    ('ReactivePower', 'MVAr'),
    ('Resistance', 'ohm'),
    ('Resistance', 'pu'),
    ('StartFuelPerCapacity', 'MMBtu/MW'),
    ('Susceptance', 'S'),
    ('Susceptance', 'pu'),
    ('Voltage', 'kV'),
    ('Voltage', 'pu'),
    ('Volume', 'm3'),
    ('VolumeFlowRate', 'm3/s');

-- 3. Column unit conventions
INSERT INTO unit_conventions (table_name, column_name, quantity_type, unit, discriminator_column, discriminator_value, discriminator_column_2, discriminator_value_2, description) VALUES
    ('attributes', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): active power limits stored as attribute'),
    ('attributes', 'active_power_limits_pump', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): HydroPumpTurbine pump limits stored as attribute'),
    ('attributes', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): efficiency stored as attribute'),
    ('attributes', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): ramp limits stored as attribute'),
    ('attributes', 'time_limits', 'Duration', 'h', NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): time limits stored as attribute'),
    ('discrete_controlled_ac_branches', 'r', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'Resistance, per-unit on system base'),
    ('discrete_controlled_ac_branches', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Thermal rating'),
    ('discrete_controlled_ac_branches', 'x', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'Reactance, per-unit on system base'),
    ('facts_control_devices', 'regulated_bus_number', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Bus whose voltage this device regulates; 0 = local bus'),
    ('facts_control_devices', 'shunt_control_type', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Device class selecting the reactive-limit law (SVC vs STATCOM)'),
    ('facts_control_devices', 'voltage_setpoint', 'Voltage', 'kV', 'voltage_setpoint_units', 'NATURAL_UNITS', NULL, NULL, 'Sending-end voltage setpoint in kV'),
    ('facts_control_devices', 'voltage_setpoint', 'Voltage', 'pu', 'voltage_setpoint_units', 'SYSTEM_BASE', NULL, NULL, 'Sending-end voltage setpoint, pu on bus base (PSS/E VSET)'),
    ('fixed_admittance', 'y_b', 'ReactivePower', 'MVAr', 'admittance_units', 'DEVICE_MVAR', NULL, NULL, 'Shunt susceptance as Mvar at unity voltage (PSS/E BL)'),
    ('fixed_admittance', 'y_b', 'Susceptance', 'S', 'admittance_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt susceptance in siemens'),
    ('fixed_admittance', 'y_b', 'Susceptance', 'pu', 'admittance_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt susceptance, per-unit on system base'),
    ('fixed_admittance', 'y_g', 'ActivePower', 'MW', 'admittance_units', 'DEVICE_MVAR', NULL, NULL, 'Shunt conductance as MW at unity voltage (PSS/E GL)'),
    ('fixed_admittance', 'y_g', 'Conductance', 'S', 'admittance_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt conductance in siemens'),
    ('fixed_admittance', 'y_g', 'Conductance', 'pu', 'admittance_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt conductance, per-unit on system base'),
    ('hydro_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('hydro_generators', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('hydro_generators', 'conversion_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, 'Conversion factor'),
    ('hydro_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('hydro_generators', 'operation_cost.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('hydro_generators', 'outflow_limits', 'VolumeFlowRate', 'm3/s', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'powerhouse_elevation', 'Elevation', 'm', NULL, NULL, NULL, NULL, 'Powerhouse elevation'),
    ('hydro_generators', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('hydro_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('hydro_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('hydro_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'time_limits', 'Duration', 'h', NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('hydro_generators', 'travel_time', 'Duration', 'h', NULL, NULL, NULL, NULL, 'Water travel time'),
    ('hydro_reservoirs', 'evaporative_loss', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Standing loss from evaporation as a fraction of stored volume/energy lost per hour'),
    ('hydro_reservoirs', 'head_to_volume_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, 'Head-to-volume conversion curve (FunctionData JSON); coefficients are dimensionless in the natural-unit convention'),
    ('hydro_reservoirs', 'inflow', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'initial_level', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'intake_elevation', 'Elevation', 'm', NULL, NULL, NULL, NULL, 'Intake elevation'),
    ('hydro_reservoirs', 'level_targets', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'operation_cost', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'HydroReservoirCost (level_shortage_cost/level_surplus_cost/spillage_cost), always per unit of energy regardless of level_data_type -- level-native values are converted to energy via head_to_volume_factor before costing'),
    ('hydro_reservoirs', 'outflow', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'spillage_limits', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, 'JSON {min, max}'),
    ('interconnecting_converters', 'ac_setpoint', 'PowerFactor', '1', 'ac_control', 'AC_REACTIVE_POWER', NULL, NULL, 'AC power factor setpoint'),
    ('interconnecting_converters', 'ac_setpoint', 'Voltage', 'kV', 'ac_control', 'AC_VOLTAGE', 'voltage_setpoint_units', 'NATURAL_UNITS', 'AC voltage setpoint in kV'),
    ('interconnecting_converters', 'ac_setpoint', 'Voltage', 'pu', 'ac_control', 'AC_VOLTAGE', 'voltage_setpoint_units', 'SYSTEM_BASE', 'AC voltage setpoint, pu'),
    ('interconnecting_converters', 'dc_setpoint', 'ActivePower', 'MW', 'dc_control', 'DC_POWER', NULL, NULL, 'DC power demand (MW)'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'kV', 'dc_control', 'DC_VOLTAGE', 'voltage_setpoint_units', 'NATURAL_UNITS', 'DC voltage setpoint in kV'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'pu', 'dc_control', 'DC_VOLTAGE', 'voltage_setpoint_units', 'SYSTEM_BASE', 'DC voltage setpoint, pu'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'kV', 'dc_control', 'DC_VOLTAGE_DROOP', 'voltage_setpoint_units', 'NATURAL_UNITS', 'DC droop voltage setpoint in kV'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'pu', 'dc_control', 'DC_VOLTAGE_DROOP', 'voltage_setpoint_units', 'SYSTEM_BASE', 'DC droop voltage setpoint, pu'),
    ('interconnecting_converters', 'power_factor_weighting_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Reactive/active power-factor weighting fraction'),
    ('interconnecting_converters', 'remote_bus_control', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Remote bus whose voltage this converter regulates; null = local bus'),
    ('interconnecting_converters', 'rmpct', 'Fraction', '1', NULL, NULL, NULL, NULL, 'PSS/E-style remote-bus voltage-control percentage compensation'),
    ('interconnecting_converters', 'voltage_limits', 'Voltage', 'pu', NULL, NULL, NULL, NULL, 'JSON {min, max} voltage limits'),
    ('loads', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base (apparent power)'),
    ('renewable_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('renewable_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('renewable_generators', 'operation_cost.curtailment_cost', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Curtailment cost curve inside the operation_cost payload; payload power_units must be NATURAL_UNITS.'),
    ('renewable_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('renewable_generators', 'operation_cost.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'power_factor', 'PowerFactor', '1', NULL, NULL, NULL, NULL, 'Power factor'),
    ('renewable_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('renewable_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('renewable_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('sources', 'r_th', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Thevenin resistance in ohm'),
    ('sources', 'r_th', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Thevenin resistance, pu on system base'),
    ('sources', 'x_th', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Thevenin reactance in ohm'),
    ('sources', 'x_th', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Thevenin reactance, pu on system base'),
    ('storage_technologies', 'capacity_limits_charge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max} charge capacity limits'),
    ('storage_technologies', 'capacity_limits_discharge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max} discharge capacity limits'),
    ('storage_technologies', 'capacity_limits_energy', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, 'JSON {min, max} energy capacity limits'),
    ('storage_technologies', 'capital_costs_charge', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, 'Charging capital cost structure'),
    ('storage_technologies', 'capital_costs_discharge', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, 'Discharging capital cost structure'),
    ('storage_technologies', 'capital_costs_energy', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Energy capital cost structure'),
    ('storage_technologies', 'duration_limits', 'Duration', 'h', NULL, NULL, NULL, NULL, 'JSON {min, max} duration limits'),
    ('storage_technologies', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, 'JSON {in, out} efficiency'),
    ('storage_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('storage_technologies', 'lifetime', 'Duration', 'yr', NULL, NULL, NULL, NULL, 'Technology lifetime'),
    ('storage_technologies', 'losses', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Storage losses'),
    ('storage_technologies', 'min_discharge_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Minimum discharge fraction'),
    ('storage_technologies', 'operation_costs.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Shut-down cost (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Start-up cost (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_costs JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_technologies', 'unit_size_charge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Charging unit size'),
    ('storage_technologies', 'unit_size_discharge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Discharging unit size'),
    ('storage_technologies', 'unit_size_energy', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, 'Energy storage unit size'),
    ('storage_units', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('storage_units', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('storage_units', 'conversion_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, 'Conversion factor'),
    ('storage_units', 'cycle_limits', 'Dimensionless', '1', NULL, NULL, NULL, NULL, 'Maximum number of charge/discharge cycles (dimensionless count)'),
    ('storage_units', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, 'JSON {in, out} efficiency'),
    ('storage_units', 'initial_storage_capacity_level', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Initial storage level as ratio [0, 1] of storage_capacity'),
    ('storage_units', 'input_active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max} charging'),
    ('storage_units', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('storage_units', 'operation_cost.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Shut-down cost (operation_cost JSON path)'),
    ('storage_units', 'operation_cost.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Start-up cost (operation_cost JSON path)'),
    ('storage_units', 'operation_cost.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'output_active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max} discharging'),
    ('storage_units', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, 'JSON {up, down} ramp limits'),
    ('storage_units', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('storage_units', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('storage_units', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('storage_units', 'self_discharge', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Leakage loss as a fraction of stored energy lost per hour'),
    ('storage_units', 'standing_loss', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Constant standing-loss power'),
    ('storage_units', 'storage_capacity', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, 'Total storage capacity'),
    ('storage_units', 'storage_level_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, 'JSON {min, max} as ratio [0, 1] of storage_capacity'),
    ('storage_units', 'storage_target', 'Fraction', '1', NULL, NULL, NULL, NULL, 'End-of-simulation storage target as ratio of storage_capacity'),
    ('supply_technologies', 'capacity_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max} capacity limits'),
    ('supply_technologies', 'capital_costs', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, 'Capital cost structure'),
    ('supply_technologies', 'co2', 'CO2Emissions', 't/MMBtu', NULL, NULL, NULL, NULL, 'JSON CO2 emission rates per fuel'),
    ('supply_technologies', 'cofire_level_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, 'JSON fuel cofire level limits'),
    ('supply_technologies', 'cofire_start_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, 'JSON fuel cofire start limits'),
    ('supply_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('supply_technologies', 'lifetime', 'Duration', 'yr', NULL, NULL, NULL, NULL, 'Technology lifetime'),
    ('supply_technologies', 'min_generation_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Minimum generation fraction'),
    ('supply_technologies', 'operation_costs.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Shut-down cost (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Start-up cost (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_costs JSON path); payload power_units must be NATURAL_UNITS'),
    ('supply_technologies', 'outage_factor', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Outage factor'),
    ('supply_technologies', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, 'JSON {up, down} ramp limits'),
    ('supply_technologies', 'start_fuel_mmbtu_per_mw', 'StartFuelPerCapacity', 'MMBtu/MW', NULL, NULL, NULL, NULL, 'Start-up fuel per unit of capacity'),
    ('supply_technologies', 'time_limits', 'Duration', 'h', NULL, NULL, NULL, NULL, 'JSON {up, down} time limits'),
    ('supply_technologies', 'unit_size', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Unit nameplate capacity'),
    ('switched_admittance', 'control_mode', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Switched-shunt control mode (PSS/E MODSW)'),
    ('switched_admittance', 'regulated_bus_number', 'Fraction', '1', NULL, NULL, NULL, NULL, 'Bus whose voltage/quantity this shunt regulates; 0 = local bus'),
    ('switched_admittance', 'y_b', 'ReactivePower', 'MVAr', 'admittance_units', 'DEVICE_MVAR', NULL, NULL, 'Shunt susceptance as Mvar at unity voltage (PSS/E BL)'),
    ('switched_admittance', 'y_b', 'Susceptance', 'S', 'admittance_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt susceptance in siemens'),
    ('switched_admittance', 'y_b', 'Susceptance', 'pu', 'admittance_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt susceptance, per-unit on system base'),
    ('switched_admittance', 'y_g', 'ActivePower', 'MW', 'admittance_units', 'DEVICE_MVAR', NULL, NULL, 'Shunt conductance as MW at unity voltage (PSS/E GL)'),
    ('switched_admittance', 'y_g', 'Conductance', 'S', 'admittance_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt conductance in siemens'),
    ('switched_admittance', 'y_g', 'Conductance', 'pu', 'admittance_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt conductance, per-unit on system base'),
    ('thermal_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('thermal_generators', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('thermal_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('thermal_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('thermal_generators', 'operation_cost.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Shut-down cost (operation_cost JSON path)'),
    ('thermal_generators', 'operation_cost.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Start-up cost (operation_cost JSON path)'),
    ('thermal_generators', 'operation_cost.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('thermal_generators', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('thermal_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('thermal_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('thermal_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('thermal_generators', 'time_limits', 'Duration', 'h', NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('three_winding_transformers', 'base_power_12', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for the primary-secondary pairwise impedance'),
    ('three_winding_transformers', 'base_power_23', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for the secondary-tertiary pairwise impedance'),
    ('three_winding_transformers', 'base_power_31', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for the tertiary-primary pairwise impedance'),
    ('three_winding_transformers', 'magnetizing_shunt.imag', 'Susceptance', 'pu', NULL, NULL, NULL, NULL, 'Magnetizing shunt susceptance, pu on the primary circuit''s device base (magnetizing_shunt JSON path)'),
    ('three_winding_transformers', 'magnetizing_shunt.real', 'Conductance', 'pu', NULL, NULL, NULL, NULL, 'Magnetizing shunt conductance, pu on the primary circuit''s device base (magnetizing_shunt JSON path)'),
    ('three_winding_transformers', 'r_12', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'Measured primary-secondary resistance, pu on base_power_12 (PSS/E R1-2, CZ = 1)'),
    ('three_winding_transformers', 'r_23', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'Measured secondary-tertiary resistance, pu on base_power_23 (PSS/E R2-3, CZ = 1)'),
    ('three_winding_transformers', 'r_31', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'Measured tertiary-primary resistance, pu on base_power_31 (PSS/E R3-1, CZ = 1)'),
    ('three_winding_transformers', 'x_12', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'Measured primary-secondary reactance, pu on base_power_12 (PSS/E X1-2, CZ = 1)'),
    ('three_winding_transformers', 'x_23', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'Measured secondary-tertiary reactance, pu on base_power_23 (PSS/E X2-3, CZ = 1)'),
    ('three_winding_transformers', 'x_31', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'Measured tertiary-primary reactance, pu on base_power_31 (PSS/E X3-1, CZ = 1)'),
    ('tmodel_hvdc_lines', 'r', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'r in ohm (PSS/E native)'),
    ('tmodel_hvdc_lines', 'r', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'r, pu on system base'),
    ('transformer_circuits', 'active_power_flow', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Initial condition of active power flow through this circuit'),
    ('transformer_circuits', 'alpha', 'Angle', 'rad', NULL, NULL, NULL, NULL, 'Initial condition of phase shift across this circuit'),
    ('transformer_circuits', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Per-unit base for this circuit (apparent power)'),
    ('transformer_circuits', 'base_voltage_primary', 'Voltage', 'kV', NULL, NULL, NULL, NULL, 'Primary (from) terminal-side base voltage; reference for the circuit''s pu impedance'),
    ('transformer_circuits', 'base_voltage_secondary', 'Voltage', 'kV', NULL, NULL, NULL, NULL, 'Secondary (to) terminal-side base voltage'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} phase-angle bounds (active-power control)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} phase-angle bounds (active-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} phase-angle bounds (asymmetric active-power control)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} phase-angle bounds (asymmetric active-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'CONTROL_OF_DC_LINE', NULL, NULL, 'JSON {min, max} tap-ratio bounds (DC-line control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'CONTROL_OF_DC_LINE_DISABLED', NULL, NULL, 'JSON {min, max} tap-ratio bounds (DC-line control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'FIXED', NULL, NULL, 'JSON {min, max} tap-ratio bounds (fixed tap)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'REACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} tap-ratio bounds (reactive-power control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'REACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} tap-ratio bounds (reactive-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'UNDEFINED', NULL, NULL, 'JSON {min, max} control band; no control block'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'VOLTAGE', NULL, NULL, 'JSON {min, max} tap-ratio bounds (voltage control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'VOLTAGE_DISABLED', NULL, NULL, 'JSON {min, max} tap-ratio bounds (voltage control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} MW band (active-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} MW band (active-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} MW band (asymmetric active-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} MW band (asymmetric active-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'CONTROL_OF_DC_LINE', NULL, NULL, 'JSON {min, max} MW band (DC-line control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'CONTROL_OF_DC_LINE_DISABLED', NULL, NULL, 'JSON {min, max} MW band (DC-line control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'FIXED', NULL, NULL, 'JSON {min, max} pu voltage band (fixed tap)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ReactivePower', 'MVAr', 'control_objective', 'REACTIVE_POWER_FLOW', NULL, NULL, 'JSON {min, max} MVAr band (reactive-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ReactivePower', 'MVAr', 'control_objective', 'REACTIVE_POWER_FLOW_DISABLED', NULL, NULL, 'JSON {min, max} MVAr band (reactive-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'UNDEFINED', NULL, NULL, 'JSON {min, max} controlled-quantity band; no control block'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'VOLTAGE', NULL, NULL, 'JSON {min, max} pu voltage band (voltage control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'VOLTAGE_DISABLED', NULL, NULL, 'JSON {min, max} pu voltage band (voltage control, disabled)'),
    ('transformer_circuits', 'r', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'Circuit resistance, pu on device base (base_power) referenced to base_voltage_primary'),
    ('transformer_circuits', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Thermal rating'),
    ('transformer_circuits', 'rating_b', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Second current rating'),
    ('transformer_circuits', 'rating_c', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Third current rating'),
    ('transformer_circuits', 'reactive_power_flow', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, 'Initial condition of reactive power flow through this circuit'),
    ('transformer_circuits', 'tap', 'Dimensionless', '1', NULL, NULL, NULL, NULL, 'Normalized tap changer position (1 = nominal voltage)'),
    ('transformer_circuits', 'x', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'Circuit reactance, pu on device base (base_power) referenced to base_voltage_primary'),
    ('transmission_interchanges', 'max_flow_from', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Maximum flow from'),
    ('transmission_interchanges', 'max_flow_to', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Maximum flow to'),
    ('transmission_lines', 'b', 'Susceptance', 'S', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt susceptance halves, JSON {from, to}, in siemens when the row''s parameter_units discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'b', 'Susceptance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt susceptance halves, JSON {from, to}, per-unit on system base when the row''s parameter_units discriminator is SYSTEM_BASE'),
    ('transmission_lines', 'continuous_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Continuous thermal rating'),
    ('transmission_lines', 'g', 'Conductance', 'S', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Shunt conductance halves, JSON {from, to}, in siemens when the row''s parameter_units discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'g', 'Conductance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Shunt conductance halves, JSON {from, to}, per-unit on system base when the row''s parameter_units discriminator is SYSTEM_BASE'),
    ('transmission_lines', 'line_length', 'Length', 'km', NULL, NULL, NULL, NULL, 'Line length'),
    ('transmission_lines', 'lte_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Long-term emergency rating'),
    ('transmission_lines', 'r', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Series resistance in ohm when the row''s parameter_units discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'r', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Series resistance, per-unit on system base when the row''s parameter_units discriminator is SYSTEM_BASE'),
    ('transmission_lines', 'ste_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, 'Short-term emergency rating'),
    ('transmission_lines', 'x', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'Series reactance in ohm when the row''s parameter_units discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'x', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'Series reactance, per-unit on system base when the row''s parameter_units discriminator is SYSTEM_BASE'),
    ('transport_technologies', 'capital_costs', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, 'Capital cost structure'),
    ('transport_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('transport_technologies', 'unit_size', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, 'Unit nameplate capacity'),
    ('two_terminal_lcc_lines', 'compounding_resistance', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'compounding_resistance in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'compounding_resistance', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'compounding_resistance, pu on system base'),
    ('two_terminal_lcc_lines', 'inverter_capacitor_reactance', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'inverter_capacitor_reactance in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'inverter_capacitor_reactance', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'inverter_capacitor_reactance, pu on system base'),
    ('two_terminal_lcc_lines', 'inverter_rc', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'inverter_rc in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'inverter_rc', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'inverter_rc, pu on system base'),
    ('two_terminal_lcc_lines', 'inverter_xc', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'inverter_xc in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'inverter_xc', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'inverter_xc, pu on system base'),
    ('two_terminal_lcc_lines', 'min_compounding_voltage', 'Voltage', 'kV', 'dc_voltage_units', 'NATURAL_UNITS', NULL, NULL, 'min_compounding_voltage in kV (PSS/E native)'),
    ('two_terminal_lcc_lines', 'min_compounding_voltage', 'Voltage', 'pu', 'dc_voltage_units', 'SYSTEM_BASE', NULL, NULL, 'min_compounding_voltage, pu on DC base voltage'),
    ('two_terminal_lcc_lines', 'r', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'r in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'r', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'r, pu on system base'),
    ('two_terminal_lcc_lines', 'rectifier_capacitor_reactance', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'rectifier_capacitor_reactance in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'rectifier_capacitor_reactance', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'rectifier_capacitor_reactance, pu on system base'),
    ('two_terminal_lcc_lines', 'rectifier_rc', 'Resistance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'rectifier_rc in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'rectifier_rc', 'Resistance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'rectifier_rc, pu on system base'),
    ('two_terminal_lcc_lines', 'rectifier_xc', 'Reactance', 'ohm', 'parameter_units', 'NATURAL_UNITS', NULL, NULL, 'rectifier_xc in ohm (PSS/E native)'),
    ('two_terminal_lcc_lines', 'rectifier_xc', 'Reactance', 'pu', 'parameter_units', 'SYSTEM_BASE', NULL, NULL, 'rectifier_xc, pu on system base'),
    ('two_terminal_lcc_lines', 'scheduled_dc_voltage', 'Voltage', 'kV', 'dc_voltage_units', 'NATURAL_UNITS', NULL, NULL, 'scheduled_dc_voltage in kV (PSS/E native)'),
    ('two_terminal_lcc_lines', 'scheduled_dc_voltage', 'Voltage', 'pu', 'dc_voltage_units', 'SYSTEM_BASE', NULL, NULL, 'scheduled_dc_voltage, pu on DC base voltage'),
    ('two_terminal_lcc_lines', 'switch_mode_voltage', 'Voltage', 'kV', 'dc_voltage_units', 'NATURAL_UNITS', NULL, NULL, 'switch_mode_voltage in kV (PSS/E native)'),
    ('two_terminal_lcc_lines', 'switch_mode_voltage', 'Voltage', 'pu', 'dc_voltage_units', 'SYSTEM_BASE', NULL, NULL, 'switch_mode_voltage, pu on DC base voltage'),
    ('two_terminal_vsc_lines', 'ac_setpoint_from', 'PowerFactor', '1', 'ac_control_from', 'AC_REACTIVE_POWER', NULL, NULL, 'AC power factor setpoint'),
    ('two_terminal_vsc_lines', 'ac_setpoint_from', 'Voltage', 'kV', 'ac_control_from', 'AC_VOLTAGE', 'voltage_units', 'NATURAL_UNITS', 'AC voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'ac_setpoint_from', 'Voltage', 'pu', 'ac_control_from', 'AC_VOLTAGE', 'voltage_units', 'SYSTEM_BASE', 'AC voltage setpoint, pu on bus base'),
    ('two_terminal_vsc_lines', 'ac_setpoint_to', 'PowerFactor', '1', 'ac_control_to', 'AC_REACTIVE_POWER', NULL, NULL, 'AC power factor setpoint'),
    ('two_terminal_vsc_lines', 'ac_setpoint_to', 'Voltage', 'kV', 'ac_control_to', 'AC_VOLTAGE', 'voltage_units', 'NATURAL_UNITS', 'AC voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'ac_setpoint_to', 'Voltage', 'pu', 'ac_control_to', 'AC_VOLTAGE', 'voltage_units', 'SYSTEM_BASE', 'AC voltage setpoint, pu on bus base'),
    ('two_terminal_vsc_lines', 'dc_setpoint_from', 'ActivePower', 'MW', 'dc_control_from', 'DC_POWER', NULL, NULL, 'DC power demand (MW)'),
    ('two_terminal_vsc_lines', 'dc_setpoint_from', 'Voltage', 'kV', 'dc_control_from', 'DC_VOLTAGE', 'voltage_units', 'NATURAL_UNITS', 'DC voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'dc_setpoint_from', 'Voltage', 'pu', 'dc_control_from', 'DC_VOLTAGE', 'voltage_units', 'SYSTEM_BASE', 'DC voltage setpoint, pu on DC base'),
    ('two_terminal_vsc_lines', 'dc_setpoint_from', 'Voltage', 'kV', 'dc_control_from', 'DC_VOLTAGE_DROOP', 'voltage_units', 'NATURAL_UNITS', 'DC droop voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'dc_setpoint_from', 'Voltage', 'pu', 'dc_control_from', 'DC_VOLTAGE_DROOP', 'voltage_units', 'SYSTEM_BASE', 'DC droop voltage setpoint, pu'),
    ('two_terminal_vsc_lines', 'dc_setpoint_to', 'ActivePower', 'MW', 'dc_control_to', 'DC_POWER', NULL, NULL, 'DC power demand (MW)'),
    ('two_terminal_vsc_lines', 'dc_setpoint_to', 'Voltage', 'kV', 'dc_control_to', 'DC_VOLTAGE', 'voltage_units', 'NATURAL_UNITS', 'DC voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'dc_setpoint_to', 'Voltage', 'pu', 'dc_control_to', 'DC_VOLTAGE', 'voltage_units', 'SYSTEM_BASE', 'DC voltage setpoint, pu on DC base'),
    ('two_terminal_vsc_lines', 'dc_setpoint_to', 'Voltage', 'kV', 'dc_control_to', 'DC_VOLTAGE_DROOP', 'voltage_units', 'NATURAL_UNITS', 'DC droop voltage setpoint in kV'),
    ('two_terminal_vsc_lines', 'dc_setpoint_to', 'Voltage', 'pu', 'dc_control_to', 'DC_VOLTAGE_DROOP', 'voltage_units', 'SYSTEM_BASE', 'DC droop voltage setpoint, pu'),
    ('two_terminal_vsc_lines', 'g', 'ActivePower', 'MW', 'admittance_units', 'DEVICE_MVAR', NULL, NULL, 'Converter conductance as MW at unity voltage'),
    ('two_terminal_vsc_lines', 'g', 'Conductance', 'S', 'admittance_units', 'NATURAL_UNITS', NULL, NULL, 'Converter conductance in siemens'),
    ('two_terminal_vsc_lines', 'g', 'Conductance', 'pu', 'admittance_units', 'SYSTEM_BASE', NULL, NULL, 'Converter conductance, pu on system base'),
    ('two_terminal_vsc_lines', 'voltage_limits_from', 'Voltage', 'kV', 'voltage_units', 'NATURAL_UNITS', NULL, NULL, 'JSON {min, max} DC bus voltage limits at the from-converter, in kV'),
    ('two_terminal_vsc_lines', 'voltage_limits_from', 'Voltage', 'pu', 'voltage_units', 'SYSTEM_BASE', NULL, NULL, 'JSON {min, max} DC bus voltage limits at the from-converter, pu on DC base voltage'),
    ('two_terminal_vsc_lines', 'voltage_limits_to', 'Voltage', 'kV', 'voltage_units', 'NATURAL_UNITS', NULL, NULL, 'JSON {min, max} DC bus voltage limits at the to-converter, in kV'),
    ('two_terminal_vsc_lines', 'voltage_limits_to', 'Voltage', 'pu', 'voltage_units', 'SYSTEM_BASE', NULL, NULL, 'JSON {min, max} DC bus voltage limits at the to-converter, pu on DC base voltage'),
    ('two_winding_transformers', 'magnetizing_shunt.imag', 'Susceptance', 'pu', NULL, NULL, NULL, NULL, 'Magnetizing shunt susceptance, pu on the circuit''s device base (magnetizing_shunt JSON path)'),
    ('two_winding_transformers', 'magnetizing_shunt.real', 'Conductance', 'pu', NULL, NULL, NULL, NULL, 'Magnetizing shunt conductance, pu on the circuit''s device base (magnetizing_shunt JSON path)');

-- 4. Registry metadata (non-seal rows)
INSERT INTO unit_management_metadata (key, value, description) VALUES
    ('convention', 'sienna-griddb-1.1', 'Schema unit convention version'),
    ('units_artifact', 'sienna-units-1.0', 'SiennaSchemas Core/units.json vocabulary convention this registry derives from');

-- 5. Seal row -- sha256 over canonical repr of the registry.
-- Inserting this row activates the immutability triggers. See the
-- module docstring of generate_unit_registry.py for the exact repr.
INSERT INTO unit_management_metadata (key, value, description) VALUES
    ('unit_conventions_checksum', 'a039555e2f8674e24e0d207dcafc04057c5af742925802343d704b3f9be1378b', 'Registry content fingerprint -- verify with scripts/verify_unit_registry.py');
