PRAGMA foreign_keys = ON;

-- Unit Registry Seed Data (GENERATED -- do not edit by hand)
-- Regenerate with: python3 scripts/generate_unit_registry.py
-- Source of truth: SiennaSchemas Core/units.json + schema/column_conventions.json
-- Must run AFTER schema.sql and triggers.sql, BEFORE views.sql.

-- 1. Quantity types
INSERT INTO quantity_types (name, default_unit, dimension, description) VALUES
    ('ActivePower', 'MW', '{"L":2,"M":1,"T":-3}', 'Active (real) power'),
    ('ActivePowerChangeRate', 'MW/min', '{"L":2,"M":1,"T":-4}', 'Rate of change of active power (ramp)'),
    ('Angle', 'rad', '{}', 'Angle (allowed units rad and deg)'),
    ('ApparentPower', 'MVA', '{"L":2,"M":1,"T":-3}', 'Apparent power'),
    ('CO2Emissions', 't/MMBtu', '{"Btu":-1,"M":1}', 'CO2 emission rate (mass per unit of fuel energy)'),
    ('CalendarPeriod', 'yr', '{"T":1}', 'Long-term planning span, a whole number of years. Integer-valued. Deliberately carries no to_default bridge into Duration or OperationalDuration: a calendar year is not a fixed number of seconds, so any such factor would silently bake in a 365-day convention.'),
    ('Capacitance', 'F', '{"I":2,"L":-2,"M":-1,"T":4}', 'Capacitance'),
    ('Conductance', 'S', '{"I":2,"L":-2,"M":-1,"T":3}', 'Conductance'),
    ('CostPerCapacity', 'USD/MW', '{"L":-2,"M":-1,"T":3,"USD":1}', 'Cost per unit of capacity (capital cost)'),
    ('CostPerEnergy', 'USD/MWh', '{"L":-2,"M":-1,"T":2,"USD":1}', 'Cost per unit of energy (operation / energy capital cost)'),
    ('CostPerLevel', 'USD/m', '{"L":-1,"USD":1}', 'Cost per unit of hydraulic head (e.g. reservoir operation cost when level_data_type=HEAD)'),
    ('CostPerMass', 'USD/t', '{"M":-1,"USD":1}', 'Cost per unit of mass (e.g. carbon price or tax)'),
    ('CostPerTime', 'USD/h', '{"T":-1,"USD":1}', 'Cost per unit of time'),
    ('CostPerVolume', 'USD/m3', '{"L":-3,"USD":1}', 'Cost per unit of volume (e.g. reservoir operation cost)'),
    ('CurrentFlow', 'kA', '{"I":1}', 'Current flow'),
    ('Dimensionless', '1', '{}', 'Dimensionless quantity'),
    ('Duration', 's', '{"T":1}', 'Continuous-time duration or time constant, real-valued seconds. Dynamics time constants are inherently fractional, so no integer representation exists for them. Discrete scheduling durations use OperationalDuration; multi-year planning spans use CalendarPeriod.'),
    ('ElectricalEnergy', 'MWh', '{"L":2,"M":1,"T":-2}', 'Real (electrical) energy'),
    ('Elevation', 'm', '{"L":1}', 'Elevation / hydraulic head'),
    ('EmissionRate', 't/MWh', '{"L":-2,"T":2}', 'Emission mass per unit of electrical energy'),
    ('Fraction', '1', '{}', 'Fractional quantity (efficiency, losses, cofire level, etc.)'),
    ('FractionPerTime', '1/min', '{"T":-1}', 'A fraction of a stored quantity lost or decayed per unit of time (storage self-discharge, leakage). Per minute, matching OperationalDuration: the value multiplies the simulation step, so its time basis must be the same one durations use or the decay is wrong by the ratio of the two. Distinct from Frequency despite sharing the T^-1 dimension.'),
    ('Frequency', 'Hz', '{"T":-1}', 'Frequency'),
    ('HeadRate', 'm/s', '{"L":1,"T":-1}', 'Rate of change of hydraulic head'),
    ('HeatRate', 'MMBtu/MWh', '{"Btu":1,"L":-2,"M":-1,"T":2}', 'Heat rate (fuel energy per unit of electrical energy)'),
    ('Impedance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Impedance'),
    ('Inductance', 'H', '{"I":-2,"L":2,"M":1,"T":-2}', 'Inductance'),
    ('Length', 'km', '{"L":1}', 'Length'),
    ('Mass', 't', '{"M":1}', 'Mass'),
    ('Money', 'USD', '{"USD":1}', 'Monetary value'),
    ('OperationalDuration', 'min', '{"T":1}', 'Operational or scheduling duration, expressed in minutes. The unit is the convention; integrality is not. Most of these fields are real-valued because the data model library validates them on an open (0, nothing) range and sub-minute products are legitimate (a 30-second reserve, a fractional-minute saturation window). Declare a field integer only where the domain is genuinely discrete and the ingest path rounds -- mean_time_to_recovery is the current example. Sub-minute control timing belongs in Duration instead.'),
    ('PowerFactor', '1', '{}', 'Power factor'),
    ('PowerPerFrequency', 'MW/Hz', '{"L":2,"M":1,"T":-2}', 'Active power response per unit of frequency deviation (regulation / droop participation)'),
    ('Reactance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Reactance'),
    ('ReactivePower', 'MVAr', '{"L":2,"M":1,"T":-3}', 'Reactive power'),
    ('Resistance', 'ohm', '{"I":-2,"L":2,"M":1,"T":-3}', 'Resistance'),
    ('StartFuelPerCapacity', 'MMBtu/MW', '{"Btu":1,"L":-2,"M":-1,"T":3}', 'Start-up fuel per unit of capacity'),
    ('Susceptance', 'S', '{"I":2,"L":-2,"M":-1,"T":3}', 'Susceptance'),
    ('Voltage', 'kV', '{"I":-1,"L":2,"M":1,"T":-3}', 'Voltage'),
    ('Volume', 'm3', '{"L":3}', 'Volume'),
    ('VolumeFlowRate', 'm3/s', '{"L":3,"T":-1}', 'Volumetric flow rate');

-- 2. Allowed (quantity_type, unit) vocabulary
INSERT INTO allowed_units (quantity_type, unit) VALUES
    ('ActivePower', 'GW'),
    ('ActivePower', 'MW'),
    ('ActivePower', 'TW'),
    ('ActivePower', 'kW'),
    ('ActivePowerChangeRate', 'MW/min'),
    ('Angle', 'deg'),
    ('Angle', 'rad'),
    ('ApparentPower', 'MVA'),
    ('CO2Emissions', 't/MMBtu'),
    ('CalendarPeriod', 'yr'),
    ('Capacitance', 'F'),
    ('Conductance', 'S'),
    ('Conductance', 'pu'),
    ('CostPerCapacity', 'USD/MW'),
    ('CostPerEnergy', 'USD/MWh'),
    ('CostPerLevel', 'USD/m'),
    ('CostPerMass', 'USD/t'),
    ('CostPerTime', 'USD/h'),
    ('CostPerVolume', 'USD/m3'),
    ('CurrentFlow', 'A'),
    ('CurrentFlow', 'kA'),
    ('Dimensionless', '1'),
    ('Duration', 's'),
    ('ElectricalEnergy', 'GWh'),
    ('ElectricalEnergy', 'MJ'),
    ('ElectricalEnergy', 'MWh'),
    ('ElectricalEnergy', 'MWmin'),
    ('ElectricalEnergy', 'TWh'),
    ('ElectricalEnergy', 'kWh'),
    ('Elevation', 'm'),
    ('EmissionRate', 'Mt/MWh'),
    ('EmissionRate', 't/MWh'),
    ('Fraction', '1'),
    ('FractionPerTime', '1/min'),
    ('Frequency', 'Hz'),
    ('HeadRate', 'm/s'),
    ('HeatRate', 'MMBtu/MWh'),
    ('Impedance', 'ohm'),
    ('Inductance', 'H'),
    ('Length', 'km'),
    ('Length', 'm'),
    ('Mass', 'Mt'),
    ('Mass', 'kg'),
    ('Mass', 'lb'),
    ('Mass', 'ston'),
    ('Mass', 't'),
    ('Money', 'USD'),
    ('OperationalDuration', 'min'),
    ('PowerFactor', '1'),
    ('PowerPerFrequency', 'MW/Hz'),
    ('Reactance', 'ohm'),
    ('Reactance', 'pu'),
    ('ReactivePower', 'MVAr'),
    ('Resistance', 'ohm'),
    ('Resistance', 'pu'),
    ('StartFuelPerCapacity', 'MMBtu/MW'),
    ('Susceptance', 'S'),
    ('Susceptance', 'pu'),
    ('Voltage', 'kV'),
    ('Voltage', 'pu'),
    ('Volume', 'm3'),
    ('VolumeFlowRate', 'm3/s');

-- 3. Column unit conventions
INSERT INTO unit_conventions (table_name, column_name, quantity_type, unit, discriminator_column, discriminator_value, discriminator_column_2, discriminator_value_2, base_power_ref, base_voltage_ref, description) VALUES
    ('attributes', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): active power setpoint stored as attribute'),
    ('attributes', 'active_power_flow', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): branch active power flow stored as attribute'),
    ('attributes', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): active power limits stored as attribute'),
    ('attributes', 'active_power_limits_pump', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): HydroPumpTurbine pump limits stored as attribute'),
    ('attributes', 'angle', 'Angle', 'rad', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): bus voltage angle stored as attribute'),
    ('attributes', 'angle_limits', 'Angle', 'rad', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): branch phase-angle-difference limits stored as attribute'),
    ('attributes', 'base_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): bus base voltage stored as attribute'),
    ('attributes', 'capacity_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): transport technology capacity band; unit inferred from the supply_technologies.capacity_limits precedent, not from an x-unit annotation stored as attribute'),
    ('attributes', 'dc_current', 'CurrentFlow', 'A', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC DC current stored as attribute'),
    ('attributes', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): efficiency stored as attribute'),
    ('attributes', 'inverter_base_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter commutating base voltage stored as attribute'),
    ('attributes', 'inverter_bridges', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter bridge count stored as attribute'),
    ('attributes', 'inverter_extinction_angle', 'Angle', 'deg', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter extinction angle stored as attribute'),
    ('attributes', 'inverter_extinction_angle_limits', 'Angle', 'deg', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter extinction-angle limits stored as attribute'),
    ('attributes', 'inverter_tap_limits', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter tap limits stored as attribute'),
    ('attributes', 'inverter_tap_setting', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter tap setting stored as attribute'),
    ('attributes', 'inverter_tap_step', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter tap step stored as attribute'),
    ('attributes', 'inverter_transformer_ratio', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC inverter transformer ratio stored as attribute'),
    ('attributes', 'load_response', 'PowerPerFrequency', 'MW/Hz', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): area load-frequency response stored as attribute'),
    ('attributes', 'magnitude', 'Voltage', 'pu', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): bus voltage magnitude, pu on base_voltage stored as attribute'),
    ('attributes', 'max_active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): maximum active power demand stored as attribute'),
    ('attributes', 'max_dc_current_from', 'CurrentFlow', 'A', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-converter DC current ceiling stored as attribute'),
    ('attributes', 'max_dc_current_to', 'CurrentFlow', 'A', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-converter DC current ceiling stored as attribute'),
    ('attributes', 'max_reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): maximum reactive power demand stored as attribute'),
    ('attributes', 'peak_active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): area/zone peak active power stored as attribute'),
    ('attributes', 'peak_demand_mw', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): demand requirement peak demand stored as attribute'),
    ('attributes', 'peak_reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): area/zone peak reactive power stored as attribute'),
    ('attributes', 'power_factor_weighting_fraction_from', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-converter power-factor weighting stored as attribute'),
    ('attributes', 'power_factor_weighting_fraction_to', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-converter power-factor weighting stored as attribute'),
    ('attributes', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): ramp limits stored as attribute'),
    ('attributes', 'rated_ac_voltage_from', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-converter rated AC voltage stored as attribute'),
    ('attributes', 'rated_ac_voltage_to', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-converter rated AC voltage stored as attribute'),
    ('attributes', 'rated_dc_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC rated DC voltage stored as attribute'),
    ('attributes', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): device rating stored as attribute'),
    ('attributes', 'rating_from', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-converter rating stored as attribute'),
    ('attributes', 'rating_to', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-converter rating stored as attribute'),
    ('attributes', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): reactive power setpoint stored as attribute'),
    ('attributes', 'reactive_power_flow', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): branch reactive power flow stored as attribute'),
    ('attributes', 'reactive_power_from', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-terminal reactive power stored as attribute'),
    ('attributes', 'reactive_power_to', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-terminal reactive power stored as attribute'),
    ('attributes', 'rectifier_base_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier commutating base voltage stored as attribute'),
    ('attributes', 'rectifier_bridges', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier bridge count stored as attribute'),
    ('attributes', 'rectifier_delay_angle', 'Angle', 'deg', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier firing (delay) angle stored as attribute'),
    ('attributes', 'rectifier_delay_angle_limits', 'Angle', 'deg', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier firing-angle limits stored as attribute'),
    ('attributes', 'rectifier_tap_limits', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier tap limits stored as attribute'),
    ('attributes', 'rectifier_tap_setting', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier tap setting stored as attribute'),
    ('attributes', 'rectifier_tap_step', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier tap step stored as attribute'),
    ('attributes', 'rectifier_transformer_ratio', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): LCC rectifier transformer ratio stored as attribute'),
    ('attributes', 'rmpct_from', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC from-converter remote-regulation share stored as attribute'),
    ('attributes', 'rmpct_to', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): VSC to-converter remote-regulation share stored as attribute'),
    ('attributes', 'start_fuel_mmbtu_per_mw', 'StartFuelPerCapacity', 'MMBtu/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): start fuel per unit capacity; mirrors the supply_technologies column stored as attribute'),
    ('attributes', 'time_at_status', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): time spent in the current on/off status stored as attribute'),
    ('attributes', 'time_limits', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): time limits stored as attribute'),
    ('attributes', 'value_of_lost_load', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): value of lost load stored as attribute'),
    ('attributes', 'voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): transport technology voltage class stored as attribute'),
    ('attributes', 'voltage_limits', 'Voltage', 'pu', NULL, NULL, NULL, NULL, NULL, NULL, 'Attribute-name convention (not a physical column): bus voltage limits, pu on base_voltage stored as attribute'),
    ('balancing_topologies', 'base_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Nominal (base) voltage of this bus; referenced as the base for pu impedance/admittance conventions elsewhere in the schema'),
    ('discrete_controlled_ac_branches', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-row snapshot of the system base that r/x is normalized against'),
    ('discrete_controlled_ac_branches', 'r', 'Resistance', 'pu', NULL, NULL, NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Resistance, per-unit on system base'),
    ('discrete_controlled_ac_branches', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Thermal rating'),
    ('discrete_controlled_ac_branches', 'x', 'Reactance', 'pu', NULL, NULL, NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Reactance, per-unit on system base'),
    ('facts_control_devices', 'regulated_bus_number', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Bus whose voltage this device regulates; 0 = local bus'),
    ('facts_control_devices', 'shunt_control_type', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Device class selecting the reactive-limit law (SVC vs STATCOM)'),
    ('facts_control_devices', 'voltage_setpoint', 'Voltage', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, NULL, 'bus->balancing_topologies.base_voltage', 'Sending-end voltage setpoint, pu on bus base'),
    ('facts_control_devices', 'voltage_setpoint', 'Voltage', 'kV', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Sending-end voltage setpoint in kV'),
    ('fixed_admittance', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-row snapshot of the system base that the COMPONENT_BASE arm of y_g/y_b is normalized against'),
    ('fixed_admittance', 'y_b', 'Susceptance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'bus->balancing_topologies.base_voltage', 'Shunt susceptance, per-unit on system base'),
    ('fixed_admittance', 'y_b', 'Susceptance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt susceptance in siemens'),
    ('fixed_admittance', 'y_b', 'ReactivePower', 'MVAr', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt susceptance in the PSS/E form: MVAr at 1.0 pu voltage'),
    ('fixed_admittance', 'y_g', 'Conductance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'bus->balancing_topologies.base_voltage', 'Shunt conductance, per-unit on system base'),
    ('fixed_admittance', 'y_g', 'Conductance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt conductance in siemens'),
    ('fixed_admittance', 'y_g', 'ActivePower', 'MW', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt conductance in the PSS/E form: MW at 1.0 pu voltage'),
    ('hydro_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('hydro_generators', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('hydro_generators', 'conversion_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Conversion factor'),
    ('hydro_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('hydro_generators', 'outflow_limits', 'VolumeFlowRate', 'm3/s', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'powerhouse_elevation', 'Elevation', 'm', NULL, NULL, NULL, NULL, NULL, NULL, 'Powerhouse elevation'),
    ('hydro_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'AVERAGE_RATE', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Average-rate cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('hydro_generators', 'production_cost', 'HeatRate', 'MMBtu/MWh', 'production_cost.value_curve.curve_type', 'AVERAGE_RATE', 'production_cost.variable_cost_type', 'FUEL', NULL, NULL, 'Average heat rate of a FuelCurve; the money is carried separately by fuel_cost (production_cost column)'),
    ('hydro_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'INCREMENTAL', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Incremental (marginal) cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('hydro_generators', 'production_cost', 'HeatRate', 'MMBtu/MWh', 'production_cost.value_curve.curve_type', 'INCREMENTAL', 'production_cost.variable_cost_type', 'FUEL', NULL, NULL, 'Incremental heat rate of a FuelCurve; the money is carried separately by fuel_cost (production_cost column)'),
    ('hydro_generators', 'production_cost', 'CostPerTime', 'USD/h', 'production_cost.value_curve.curve_type', 'INPUT_OUTPUT', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Input-output cost curve: the y coordinate is a cost rate at a power level, not a marginal cost (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('hydro_generators', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('hydro_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('hydro_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('hydro_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_generators', 'time_limits', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('hydro_generators', 'travel_time', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'Water travel time'),
    ('hydro_reservoirs', 'evaporative_loss', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Standing loss from evaporation as a fraction of stored volume/energy lost per hour'),
    ('hydro_reservoirs', 'head_to_volume_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Head-to-volume conversion curve (FunctionData JSON); coefficients are dimensionless in the natural-unit convention'),
    ('hydro_reservoirs', 'inflow', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'inflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'Inflow rate'),
    ('hydro_reservoirs', 'initial_level', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'initial_level', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'Initial reservoir level'),
    ('hydro_reservoirs', 'intake_elevation', 'Elevation', 'm', NULL, NULL, NULL, NULL, NULL, NULL, 'Intake elevation'),
    ('hydro_reservoirs', 'level_targets', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'level_targets', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'Reservoir level targets'),
    ('hydro_reservoirs', 'operation_cost', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'HydroReservoirCost (level_shortage_cost/level_surplus_cost/spillage_cost), always per unit of energy regardless of level_data_type -- level-native values are converted to energy via head_to_volume_factor before costing'),
    ('hydro_reservoirs', 'outflow', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'outflow', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'Outflow rate'),
    ('hydro_reservoirs', 'spillage_limits', 'ActivePower', 'MW', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'HeadRate', 'm/s', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'spillage_limits', 'VolumeFlowRate', 'm3/s', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'ElectricalEnergy', 'MWh', 'level_data_type', 'ENERGY', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Elevation', 'm', 'level_data_type', 'HEAD', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Volume', 'm3', 'level_data_type', 'TOTAL_VOLUME', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('hydro_reservoirs', 'storage_level_limits', 'Volume', 'm3', 'level_data_type', 'USABLE_VOLUME', NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('interconnecting_converters', 'ac_setpoint', 'PowerFactor', '1', 'ac_control', 'AC_REACTIVE_POWER', NULL, NULL, NULL, NULL, 'AC power factor setpoint'),
    ('interconnecting_converters', 'ac_setpoint', 'Voltage', 'pu', 'ac_control', 'AC_VOLTAGE', 'unit_basis', 'COMPONENT_BASE', NULL, 'bus->balancing_topologies.base_voltage', 'AC voltage setpoint, pu'),
    ('interconnecting_converters', 'ac_setpoint', 'Voltage', 'kV', 'ac_control', 'AC_VOLTAGE', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, 'AC voltage setpoint in kV'),
    ('interconnecting_converters', 'dc_setpoint', 'ActivePower', 'MW', 'dc_control', 'DC_POWER', NULL, NULL, NULL, NULL, 'DC power demand (MW)'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'pu', 'dc_control', 'DC_VOLTAGE', 'unit_basis', 'COMPONENT_BASE', NULL, 'dc_bus->balancing_topologies.base_voltage', 'DC voltage setpoint, pu'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'kV', 'dc_control', 'DC_VOLTAGE', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, 'DC voltage setpoint in kV'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'pu', 'dc_control', 'DC_VOLTAGE_DROOP', 'unit_basis', 'COMPONENT_BASE', NULL, 'dc_bus->balancing_topologies.base_voltage', 'DC droop voltage setpoint, pu'),
    ('interconnecting_converters', 'dc_setpoint', 'Voltage', 'kV', 'dc_control', 'DC_VOLTAGE_DROOP', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, 'DC droop voltage setpoint in kV'),
    ('interconnecting_converters', 'power_factor_weighting_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Reactive/active power-factor weighting fraction'),
    ('interconnecting_converters', 'remote_bus_control', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Remote bus whose voltage this converter regulates; null = local bus'),
    ('interconnecting_converters', 'rmpct', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Remote-bus voltage-control percentage compensation'),
    ('interconnecting_converters', 'voltage_limits', 'Voltage', 'pu', NULL, NULL, NULL, NULL, NULL, 'dc_bus->balancing_topologies.base_voltage', 'JSON {min, max} voltage limits'),
    ('loads', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base (apparent power)'),
    ('renewable_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('renewable_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('renewable_generators', 'operation_cost.curtailment_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.curtailment_cost.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Curtailment average-rate cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'operation_cost.curtailment_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.curtailment_cost.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Curtailment incremental (marginal) cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'operation_cost.curtailment_cost', 'CostPerTime', 'USD/h', 'operation_cost.curtailment_cost.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Curtailment input-output cost curve: y is a cost rate at a power level (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('renewable_generators', 'power_factor', 'PowerFactor', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Power factor'),
    ('renewable_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Average-rate cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Incremental (marginal) cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'production_cost', 'CostPerTime', 'USD/h', 'production_cost.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Input-output cost curve: the y coordinate is a cost rate at a power level, not a marginal cost (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('renewable_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('renewable_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('renewable_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('sources', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Active power injection setpoint'),
    ('sources', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Active power limits (JSON min/max)'),
    ('sources', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Device power base'),
    ('sources', 'base_voltage', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Nominal voltage of the source terminal'),
    ('sources', 'internal_angle', 'Angle', 'rad', NULL, NULL, NULL, NULL, NULL, NULL, 'Internal (behind-the-impedance) voltage angle'),
    ('sources', 'internal_voltage', 'Voltage', 'pu', NULL, NULL, NULL, NULL, NULL, 'base_voltage', 'Internal (behind-the-impedance) voltage magnitude'),
    ('sources', 'operation_cost.energy_export_weekly_limit', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Weekly energy export cap of the ImportExportCost payload (operation_cost JSON path)'),
    ('sources', 'operation_cost.energy_import_weekly_limit', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Weekly energy import cap of the ImportExportCost payload (operation_cost JSON path)'),
    ('sources', 'operation_cost.export_offer_curves', 'CostPerEnergy', 'USD/MWh', 'operation_cost.export_offer_curves.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Export offer average-rate cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'operation_cost.export_offer_curves', 'CostPerEnergy', 'USD/MWh', 'operation_cost.export_offer_curves.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Export offer incremental (marginal) cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'operation_cost.export_offer_curves', 'CostPerTime', 'USD/h', 'operation_cost.export_offer_curves.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Export offer input-output cost curve: y is a cost rate at a power level (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'operation_cost.import_offer_curves', 'CostPerEnergy', 'USD/MWh', 'operation_cost.import_offer_curves.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Import offer average-rate cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'operation_cost.import_offer_curves', 'CostPerEnergy', 'USD/MWh', 'operation_cost.import_offer_curves.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Import offer incremental (marginal) cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'operation_cost.import_offer_curves', 'CostPerTime', 'USD/h', 'operation_cost.import_offer_curves.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Import offer input-output cost curve: y is a cost rate at a power level (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('sources', 'r_th', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'base_voltage', 'Thevenin resistance, pu on system base'),
    ('sources', 'r_th', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Thevenin resistance in ohm'),
    ('sources', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Reactive power injection setpoint'),
    ('sources', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Reactive power limits (JSON min/max)'),
    ('sources', 'x_th', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'base_voltage', 'Thevenin reactance, pu on system base'),
    ('sources', 'x_th', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Thevenin reactance in ohm'),
    ('storage_technologies', 'capacity_limits_charge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} charge capacity limits'),
    ('storage_technologies', 'capacity_limits_discharge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} discharge capacity limits'),
    ('storage_technologies', 'capacity_limits_energy', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} energy capacity limits'),
    ('storage_technologies', 'capital_costs_charge', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Charging capital cost structure'),
    ('storage_technologies', 'capital_costs_discharge', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Discharging capital cost structure'),
    ('storage_technologies', 'capital_costs_energy', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Energy capital cost structure'),
    ('storage_technologies', 'duration_limits', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} duration limits'),
    ('storage_technologies', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {in, out} efficiency'),
    ('storage_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('storage_technologies', 'lifetime', 'CalendarPeriod', 'yr', NULL, NULL, NULL, NULL, NULL, NULL, 'Technology lifetime'),
    ('storage_technologies', 'losses', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Storage losses'),
    ('storage_technologies', 'min_discharge_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Minimum discharge fraction'),
    ('storage_technologies', 'operation_costs.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Shut-down cost (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Start-up cost (operation_costs JSON path)'),
    ('storage_technologies', 'operation_costs.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_costs JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_technologies', 'unit_size_charge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Charging unit size'),
    ('storage_technologies', 'unit_size_discharge', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Discharging unit size'),
    ('storage_technologies', 'unit_size_energy', 'ElectricalEnergy', 'MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Energy storage unit size'),
    ('storage_units', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('storage_units', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('storage_units', 'conversion_factor', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Conversion factor'),
    ('storage_units', 'cycle_limits', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Maximum number of charge/discharge cycles (dimensionless count)'),
    ('storage_units', 'efficiency', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {in, out} efficiency'),
    ('storage_units', 'initial_storage_capacity_level', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial storage level as ratio [0, 1] of storage_capacity'),
    ('storage_units', 'input_active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} charging'),
    ('storage_units', 'operation_cost.charge_variable_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.charge_variable_cost.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Charge average-rate cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.charge_variable_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.charge_variable_cost.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Charge incremental (marginal) cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.charge_variable_cost', 'CostPerTime', 'USD/h', 'operation_cost.charge_variable_cost.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Charge input-output cost curve: y is a cost rate at a power level (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.discharge_variable_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.discharge_variable_cost.value_curve.curve_type', 'AVERAGE_RATE', NULL, NULL, NULL, NULL, 'Discharge average-rate cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.discharge_variable_cost', 'CostPerEnergy', 'USD/MWh', 'operation_cost.discharge_variable_cost.value_curve.curve_type', 'INCREMENTAL', NULL, NULL, NULL, NULL, 'Discharge incremental (marginal) cost curve (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.discharge_variable_cost', 'CostPerTime', 'USD/h', 'operation_cost.discharge_variable_cost.value_curve.curve_type', 'INPUT_OUTPUT', NULL, NULL, NULL, NULL, 'Discharge input-output cost curve: y is a cost rate at a power level (operation_cost JSON path); payload power_units must be NATURAL_UNITS'),
    ('storage_units', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('storage_units', 'operation_cost.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Shut-down cost (operation_cost JSON path)'),
    ('storage_units', 'operation_cost.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Start-up cost (operation_cost JSON path)'),
    ('storage_units', 'output_active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} discharging'),
    ('storage_units', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down} ramp limits'),
    ('storage_units', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('storage_units', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('storage_units', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('storage_units', 'self_discharge', 'FractionPerTime', '1/min', NULL, NULL, NULL, NULL, NULL, NULL, 'Leakage loss as a fraction of stored energy lost per minute'),
    ('storage_units', 'standing_loss', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Constant standing-loss power'),
    ('storage_units', 'storage_capacity', 'ElectricalEnergy', 'MWh', 'energy_units', 'MWH', NULL, NULL, NULL, NULL, 'Total storage capacity, on the MWh interchange basis when the row''s energy_units discriminator is MWH'),
    ('storage_units', 'storage_capacity', 'ElectricalEnergy', 'MWmin', 'energy_units', 'MWMIN', NULL, NULL, NULL, NULL, 'Total storage capacity, on the MWmin minutes basis when the row''s energy_units discriminator is MWMIN'),
    ('storage_units', 'storage_level_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} as ratio [0, 1] of storage_capacity'),
    ('storage_units', 'storage_target', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'End-of-simulation storage target as ratio of storage_capacity'),
    ('supply_technologies', 'capacity_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max} capacity limits'),
    ('supply_technologies', 'capital_costs', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Capital cost structure'),
    ('supply_technologies', 'co2', 'CO2Emissions', 't/MMBtu', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON CO2 emission rates per fuel'),
    ('supply_technologies', 'cofire_level_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON fuel cofire level limits'),
    ('supply_technologies', 'cofire_start_limits', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON fuel cofire start limits'),
    ('supply_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('supply_technologies', 'lifetime', 'CalendarPeriod', 'yr', NULL, NULL, NULL, NULL, NULL, NULL, 'Technology lifetime'),
    ('supply_technologies', 'min_generation_fraction', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Minimum generation fraction'),
    ('supply_technologies', 'operation_costs.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Shut-down cost (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Start-up cost (operation_costs JSON path)'),
    ('supply_technologies', 'operation_costs.variable', 'CostPerEnergy', 'USD/MWh', NULL, NULL, NULL, NULL, NULL, NULL, 'Variable cost per unit of energy (operation_costs JSON path); payload power_units must be NATURAL_UNITS'),
    ('supply_technologies', 'outage_factor', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Outage factor'),
    ('supply_technologies', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down} ramp limits'),
    ('supply_technologies', 'start_fuel_mmbtu_per_mw', 'StartFuelPerCapacity', 'MMBtu/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Start-up fuel per unit of capacity'),
    ('supply_technologies', 'time_limits', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down} time limits'),
    ('supply_technologies', 'unit_size', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Unit nameplate capacity'),
    ('switched_admittance', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-row snapshot of the system base that the COMPONENT_BASE arm of y_g/y_b is normalized against'),
    ('switched_admittance', 'control_mode', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Switched-shunt control mode'),
    ('switched_admittance', 'regulated_bus_number', 'Fraction', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Bus whose voltage/quantity this shunt regulates; 0 = local bus'),
    ('switched_admittance', 'y_b', 'Susceptance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'bus->balancing_topologies.base_voltage', 'Shunt susceptance, per-unit on system base'),
    ('switched_admittance', 'y_b', 'Susceptance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt susceptance in siemens'),
    ('switched_admittance', 'y_b', 'ReactivePower', 'MVAr', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt susceptance in the PSS/E form: MVAr at 1.0 pu voltage'),
    ('switched_admittance', 'y_g', 'Conductance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'bus->balancing_topologies.base_voltage', 'Shunt conductance, per-unit on system base'),
    ('switched_admittance', 'y_g', 'Conductance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt conductance in siemens'),
    ('switched_admittance', 'y_g', 'ActivePower', 'MW', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt conductance in the PSS/E form: MW at 1.0 pu voltage'),
    ('synchronous_condensers', 'active_power_losses', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Active power loss incurred by being online'),
    ('synchronous_condensers', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('synchronous_condensers', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Maximum AC-side output rating'),
    ('synchronous_condensers', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('synchronous_condensers', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Reactive power limits, JSON {min, max}'),
    ('thermal_generators', 'active_power', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial active power setpoint'),
    ('thermal_generators', 'active_power_limits', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('thermal_generators', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this device (apparent power)'),
    ('thermal_generators', 'operation_cost.fixed', 'CostPerTime', 'USD/h', NULL, NULL, NULL, NULL, NULL, NULL, 'Fixed cost per unit of time (operation_cost JSON path)'),
    ('thermal_generators', 'operation_cost.shut_down', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Shut-down cost (operation_cost JSON path)'),
    ('thermal_generators', 'operation_cost.start_up', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Start-up cost (operation_cost JSON path)'),
    ('thermal_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'AVERAGE_RATE', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Average-rate cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('thermal_generators', 'production_cost', 'HeatRate', 'MMBtu/MWh', 'production_cost.value_curve.curve_type', 'AVERAGE_RATE', 'production_cost.variable_cost_type', 'FUEL', NULL, NULL, 'Average heat rate of a FuelCurve; the money is carried separately by fuel_cost (production_cost column)'),
    ('thermal_generators', 'production_cost', 'CostPerEnergy', 'USD/MWh', 'production_cost.value_curve.curve_type', 'INCREMENTAL', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Incremental (marginal) cost curve (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('thermal_generators', 'production_cost', 'HeatRate', 'MMBtu/MWh', 'production_cost.value_curve.curve_type', 'INCREMENTAL', 'production_cost.variable_cost_type', 'FUEL', NULL, NULL, 'Incremental heat rate of a FuelCurve; the money is carried separately by fuel_cost (production_cost column)'),
    ('thermal_generators', 'production_cost', 'CostPerTime', 'USD/h', 'production_cost.value_curve.curve_type', 'INPUT_OUTPUT', 'production_cost.variable_cost_type', 'COST', NULL, NULL, 'Input-output cost curve: the y coordinate is a cost rate at a power level, not a marginal cost (production_cost column); payload power_units must be NATURAL_UNITS'),
    ('thermal_generators', 'ramp_limits', 'ActivePowerChangeRate', 'MW/min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('thermal_generators', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Nameplate rating'),
    ('thermal_generators', 'reactive_power', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial reactive power setpoint'),
    ('thermal_generators', 'reactive_power_limits', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {min, max}'),
    ('thermal_generators', 'time_limits', 'OperationalDuration', 'min', NULL, NULL, NULL, NULL, NULL, NULL, 'JSON {up, down}'),
    ('three_winding_transformers', 'base_power_12', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for the primary-secondary pairwise impedance'),
    ('three_winding_transformers', 'base_power_23', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for the secondary-tertiary pairwise impedance'),
    ('three_winding_transformers', 'base_power_31', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for the tertiary-primary pairwise impedance'),
    ('three_winding_transformers', 'magnetizing_shunt.imag', 'Susceptance', 'pu', NULL, NULL, NULL, NULL, 'primary_circuit->transformer_circuits.base_power', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Magnetizing shunt susceptance, pu on the primary circuit''s device base (magnetizing_shunt JSON path)'),
    ('three_winding_transformers', 'magnetizing_shunt.real', 'Conductance', 'pu', NULL, NULL, NULL, NULL, 'primary_circuit->transformer_circuits.base_power', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Magnetizing shunt conductance, pu on the primary circuit''s device base (magnetizing_shunt JSON path)'),
    ('three_winding_transformers', 'r_12', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_12', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured primary-secondary resistance, pu on base_power_12 and referred to the primary winding''s voltage base per PSSE convention, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'r_12', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured primary-secondary resistance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('three_winding_transformers', 'r_23', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_23', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured secondary-tertiary resistance, pu on base_power_23 but still referred to the primary winding''s voltage base per PSSE convention, not the secondary''s, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'r_23', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured secondary-tertiary resistance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('three_winding_transformers', 'r_31', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_31', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured tertiary-primary resistance, pu on base_power_31 but still referred to the primary winding''s voltage base per PSSE convention, not the tertiary''s, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'r_31', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured tertiary-primary resistance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('three_winding_transformers', 'x_12', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_12', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured primary-secondary reactance, pu on base_power_12 and referred to the primary winding''s voltage base per PSSE convention, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'x_12', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured primary-secondary reactance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('three_winding_transformers', 'x_23', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_23', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured secondary-tertiary reactance, pu on base_power_23 but still referred to the primary winding''s voltage base per PSSE convention, not the secondary''s, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'x_23', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured secondary-tertiary reactance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('three_winding_transformers', 'x_31', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power_31', 'primary_circuit->transformer_circuits.base_voltage_primary', 'Measured tertiary-primary reactance, pu on base_power_31 but still referred to the primary winding''s voltage base per PSSE convention, not the tertiary''s, when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('three_winding_transformers', 'x_31', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Measured tertiary-primary reactance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('tmodel_hvdc_lines', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-row snapshot of the system base that the COMPONENT_BASE arm of r is normalized against'),
    ('tmodel_hvdc_lines', 'r', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'r, pu on system base'),
    ('tmodel_hvdc_lines', 'r', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'r in ohm (native external units)'),
    ('transformer_circuits', 'active_power_flow', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial condition of active power flow through this circuit'),
    ('transformer_circuits', 'alpha', 'Angle', 'rad', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial condition of phase shift across this circuit'),
    ('transformer_circuits', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-unit base for this circuit (apparent power)'),
    ('transformer_circuits', 'base_voltage_primary', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Primary (from) terminal-side base voltage; reference for the circuit''s pu impedance'),
    ('transformer_circuits', 'base_voltage_secondary', 'Voltage', 'kV', NULL, NULL, NULL, NULL, NULL, NULL, 'Secondary (to) terminal-side base voltage'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} phase-angle bounds (active-power control)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} phase-angle bounds (active-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} phase-angle bounds (asymmetric active-power control)'),
    ('transformer_circuits', 'control_limits', 'Angle', 'rad', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} phase-angle bounds (asymmetric active-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'CONTROL_OF_DC_LINE', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (DC-line control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'CONTROL_OF_DC_LINE_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (DC-line control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'FIXED', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (fixed tap)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'REACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (reactive-power control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'REACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (reactive-power control, disabled)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'UNDEFINED', NULL, NULL, NULL, NULL, 'JSON {min, max} control band; no control block'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'VOLTAGE', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (voltage control)'),
    ('transformer_circuits', 'control_limits', 'Dimensionless', '1', 'control_objective', 'VOLTAGE_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} tap-ratio bounds (voltage control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (active-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (active-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (asymmetric active-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'ASYMMETRIC_ACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (asymmetric active-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'CONTROL_OF_DC_LINE', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (DC-line control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ActivePower', 'MW', 'control_objective', 'CONTROL_OF_DC_LINE_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} MW band (DC-line control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'FIXED', NULL, NULL, NULL, 'base_voltage_primary', 'JSON {min, max} pu voltage band (fixed tap)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ReactivePower', 'MVAr', 'control_objective', 'REACTIVE_POWER_FLOW', NULL, NULL, NULL, NULL, 'JSON {min, max} MVAr band (reactive-power control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'ReactivePower', 'MVAr', 'control_objective', 'REACTIVE_POWER_FLOW_DISABLED', NULL, NULL, NULL, NULL, 'JSON {min, max} MVAr band (reactive-power control, disabled)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'UNDEFINED', NULL, NULL, NULL, 'base_voltage_primary', 'JSON {min, max} controlled-quantity band; no control block'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'VOLTAGE', NULL, NULL, NULL, 'base_voltage_primary', 'JSON {min, max} pu voltage band (voltage control)'),
    ('transformer_circuits', 'controlled_quantity_limits', 'Voltage', 'pu', 'control_objective', 'VOLTAGE_DISABLED', NULL, NULL, NULL, 'base_voltage_primary', 'JSON {min, max} pu voltage band (voltage control, disabled)'),
    ('transformer_circuits', 'r', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'base_voltage_primary', 'Circuit resistance, per-unit on the device base (base_power referenced to base_voltage_primary) when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transformer_circuits', 'r', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Circuit resistance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transformer_circuits', 'rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Thermal rating'),
    ('transformer_circuits', 'rating_b', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Second current rating'),
    ('transformer_circuits', 'rating_c', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Third current rating'),
    ('transformer_circuits', 'reactive_power_flow', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'Initial condition of reactive power flow through this circuit'),
    ('transformer_circuits', 'tap', 'Dimensionless', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'Normalized tap changer position (1 = nominal voltage)'),
    ('transformer_circuits', 'x', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'base_voltage_primary', 'Circuit reactance, per-unit on the device base (base_power referenced to base_voltage_primary) when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transformer_circuits', 'x', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Circuit reactance, in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transmission_interchanges', 'max_flow_from', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Maximum flow from'),
    ('transmission_interchanges', 'max_flow_to', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Maximum flow to'),
    ('transmission_lines', 'b', 'Susceptance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Shunt susceptance halves, JSON {from, to}, per-unit on system base when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transmission_lines', 'b', 'Susceptance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt susceptance halves, JSON {from, to}, in siemens when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'base_power', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Per-row snapshot of the system base that the COMPONENT_BASE arm of r/x/b/g is normalized against'),
    ('transmission_lines', 'continuous_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Continuous thermal rating'),
    ('transmission_lines', 'g', 'Conductance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Shunt conductance halves, JSON {from, to}, per-unit on system base when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transmission_lines', 'g', 'Conductance', 'S', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Shunt conductance halves, JSON {from, to}, in siemens when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'line_length', 'Length', 'km', NULL, NULL, NULL, NULL, NULL, NULL, 'Line length'),
    ('transmission_lines', 'lte_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Long-term emergency rating'),
    ('transmission_lines', 'r', 'Resistance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Series resistance, per-unit on system base when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transmission_lines', 'r', 'Resistance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Series resistance in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transmission_lines', 'ste_rating', 'ApparentPower', 'MVA', NULL, NULL, NULL, NULL, NULL, NULL, 'Short-term emergency rating'),
    ('transmission_lines', 'x', 'Reactance', 'pu', 'unit_basis', 'COMPONENT_BASE', NULL, NULL, 'base_power', 'arc_id->arcs.from_id->balancing_topologies.base_voltage', 'Series reactance, per-unit on system base when the row''s unit_basis discriminator is COMPONENT_BASE'),
    ('transmission_lines', 'x', 'Reactance', 'ohm', 'unit_basis', 'NATURAL_UNITS', NULL, NULL, NULL, NULL, 'Series reactance in ohm when the row''s unit_basis discriminator is NATURAL_UNITS'),
    ('transport_technologies', 'capital_costs', 'CostPerCapacity', 'USD/MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Capital cost structure'),
    ('transport_technologies', 'financial_data', 'Money', 'USD', NULL, NULL, NULL, NULL, NULL, NULL, 'Financial parameters JSON blob; monetary values in USD'),
    ('transport_technologies', 'unit_size', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Unit nameplate capacity'),
    ('two_terminal_hvdc_lines', 'active_power_flow', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'Active power flow through the line'),
    ('two_terminal_hvdc_lines', 'active_power_limits_from', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'From-terminal active power limits'),
    ('two_terminal_hvdc_lines', 'active_power_limits_to', 'ActivePower', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, 'To-terminal active power limits'),
    ('two_terminal_hvdc_lines', 'reactive_power_limits_from', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'From-terminal reactive power limits'),
    ('two_terminal_hvdc_lines', 'reactive_power_limits_to', 'ReactivePower', 'MVAr', NULL, NULL, NULL, NULL, NULL, NULL, 'To-terminal reactive power limits'),
    ('two_winding_transformers', 'magnetizing_shunt.imag', 'Susceptance', 'pu', NULL, NULL, NULL, NULL, 'circuit->transformer_circuits.base_power', 'circuit->transformer_circuits.base_voltage_primary', 'Magnetizing shunt susceptance, pu on the circuit''s device base (magnetizing_shunt JSON path)'),
    ('two_winding_transformers', 'magnetizing_shunt.real', 'Conductance', 'pu', NULL, NULL, NULL, NULL, 'circuit->transformer_circuits.base_power', 'circuit->transformer_circuits.base_voltage_primary', 'Magnetizing shunt conductance, pu on the circuit''s device base (magnetizing_shunt JSON path)');

-- 4. Per-quantity-type pu resolution rules
INSERT INTO unit_basis_rules (quantity_type, base_expression, description) VALUES
    ('Conductance', 'base_power/base_voltage^2', 'Per-unit conductance: base admittance is base_power/base_voltage^2'),
    ('Reactance', 'base_voltage^2/base_power', 'Per-unit reactance: base impedance is base_voltage^2/base_power'),
    ('Resistance', 'base_voltage^2/base_power', 'Per-unit resistance: base impedance is base_voltage^2/base_power'),
    ('Susceptance', 'base_power/base_voltage^2', 'Per-unit susceptance: base admittance is base_power/base_voltage^2'),
    ('Voltage', 'base_voltage', 'Per-unit voltage: divide by the row''s base voltage');

-- 5. Registry metadata (non-seal rows)
INSERT INTO unit_management_metadata (key, value, description) VALUES
    ('convention', 'sienna-griddb-1.1', 'Schema unit convention version'),
    ('units_artifact', 'sienna-units-1.0', 'SiennaSchemas Core/units.json vocabulary convention this registry derives from');

-- 6. Seal row -- sha256 over canonical repr of the registry.
-- Inserting this row activates the immutability triggers. See the
-- module docstring of generate_unit_registry.py for the exact repr.
INSERT INTO unit_management_metadata (key, value, description) VALUES
    ('unit_conventions_checksum', 'cc3b3ed51d5cd9d5492a0a31e3797b98740640a6d9b07ab83e6d407b77f4c299', 'Registry content fingerprint -- verify with scripts/verify_unit_registry.py');
